webfactory_piwik:
    # Required, no default. Must be set to the site id found in the Piwik control panel
    site_id: 1
    # Required, has default. Usually, you only want to include the tracking code in a production environment
    #disabled: %kernel.debug%
    disabled: false
    # Required. no default. Hostname and path to the piwik host.
    piwik_host: piwik.local
    # Required, has default. Path to the tracking script on the host.
    tracker_path: "/js/"