doctrine_phpcr:
    session:
        backend:
            type: doctrinedbal
            connection: doctrine.dbal.default_connection
        workspace: default
        username: %doctrine_phpcr_username%
        password: %doctrine_phpcr_password%
    odm:
        auto_mapping: true