# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
#
# Support for LiipImagineBundle
#_imagine:
#    resource: .
#    type:     imagine

_admin:
    resource: routing_admin.yml
    prefix:   /admin

#_api:
#    resource: routing_api.yml
#    prefix:   /api

_front:
    resource: routing_front.yml



