cmf_routing:
    chain:
        routers_by_id:
            # enable the DynamicRouter with high priority to allow overwriting configured routes with content
            # symfony_cmf_routing_extra.dynamic_router: 200
            # enable the symfony default router with a lower priority
            sonata.page.router: 150
            #rz_news.router: 120
            router.default: 100
#
# more information can be found here http://sonata-project.org/bundles/page
#
sonata_page:
    multisite: host #host_with_path
    use_streamed_response: false # set the value to false in debug mode or if the reverse proxy does not handle streamed response
    ignore_route_patterns:
        - (.*)admin(.*)     # ignore admin route, ie route containing 'admin'
        - ^_(.*)            # ignore symfony routes
    # Generates a snapshot when a page is saved (from the admin)
    direct_publication: false # or %kernel.debug% if you want to publish in dev mode (but not in prod)
    ignore_routes:
        - sonata_page_cache_esi
        - sonata_page_cache_ssi
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_apc

    ignore_uri_patterns:
        - admin(.*)     # ignore admin route, ie route containing 'admin'

    cache_invalidation:
        service:  sonata.page.cache.invalidation.simple
        recorder: sonata.page.cache.recorder
        classes:
            "Application\Sonata\PageBundle\Entity\Block": getId

    default_template: default
    templates:
        default:
            path: 'RzPageBundle:theme\rzcms:layout.html.twig'
            name: 'Default'
            containers:
                content:
                    name: Content
                footer:
                    name: Footer
            matrix:
                layout: |
                    CCCCCCCCCCCC
                    FFFFFFFFFFFF
                mapping:
                    C: content
                    F: footer
        rzcms_homepage:
            path: 'RzPageBundle:theme\rzcms:homepage.html.twig'
            name: 'Homepage'
            containers:
                content_top:
                    name: Content Top
#                    blocks:
#                      - sonata.media.block.media
#                      - sonata.media.block.gallery
#                      - sonata.media.block.feature_media
                content:
                    name: Main Content
                content_bottom:
                    name: Content Bottom
                footer:
                    name: footer
                    shared: true
            matrix:
                layout: |
                    AAAAAAAAAAAA
                    CCCCCCCCCCCC
                    CCCCCCCCCCCC
                    CCCCCCCCCCCC
                    EEEEEEEEEEEE
                    FFFFFFFFFFFF
                mapping:
                    A: content_top
                    C: content
                    E: content_bottom
                    F: footer
        rzcms_blog:
            path: 'RzPageBundle:theme\rzcms:blog.html.twig'
            name: 'Blog'
            containers:
                content_top:
                    name: Content Top
                content:
                    name: Main Content
                news_content_right:
                    name: Content Right
                    shared: true
                content_bottom:
                    name: Content Bottom
                footer:
                    name: footer
                    shared: true
            matrix:
                layout: |
                    AAAAAAAAAAAA
                    CCCCCCCCCRRR
                    CCCCCCCCCRRR
                    CCCCCCCCCRRR
                    EEEEEEEEEEEE
                    FFFFFFFFFFFF
                mapping:
                    A: content_top
                    C: content
                    E: content_bottom
                    R: news_content_right
                    F: footer

        rzcms_blog_page:
            path: 'RzPageBundle:theme\rzcms:blog_page.html.twig'
            name: 'Blog Page List'
            containers:
                content_top:
                    name: Content Top
                content:
                    name: Main Content
                news_content_right:
                    name: Content Right
                    shared: true
                content_bottom:
                    name: Content Bottom
                footer:
                    name: footer
                    shared: true
            matrix:
                layout: |
                    AAAAAAAAAAAA
                    CCCCCCCCCRRR
                    CCCCCCCCCRRR
                    CCCCCCCCCRRR
                    EEEEEEEEEEEE
                    FFFFFFFFFFFF
                mapping:
                    A: content_top
                    C: content
                    E: content_bottom
                    R: news_content_right
                    F: footer

        rzcms_blog_category:
            path: 'RzPageBundle:theme\rzcms:blog_category.html.twig'
            name: 'Blog Category'
            containers:
                content_top:
                    name: Content Top
                content:
                    name: Main Content
                content_bottom:
                    name: Content Bottom
                footer:
                    name: footer
                    shared: true
            matrix:
                layout: |
                    AAAAAAAAAAAA
                    CCCCCCCCCCCC
                    CCCCCCCCCCCC
                    CCCCCCCCCCCC
                    EEEEEEEEEEEE
                    FFFFFFFFFFFF
                mapping:
                    A: content_top
                    C: content
                    E: content_bottom
                    F: footer

        ######################################################################
        # Required as a default template for category if controller is enabled
        ######################################################################
        rzcms_blog_page_category:
            path: 'RzPageBundle:theme\rzcms:blog_page_category.html.twig'
            name: 'Blog Page Category List'
            containers:
                content_top:
                    name: Content Top
                content:
                    name: Main Content
                content_bottom:
                    name: Content Bottom
                footer:
                    name: footer
                    shared: true
            matrix:
                layout: |
                    AAAAAAAAAAAA
                    CCCCCCCCCCCC
                    CCCCCCCCCCCC
                    CCCCCCCCCCCC
                    EEEEEEEEEEEE
                    FFFFFFFFFFFF
                mapping:
                    A: content_top
                    C: content
                    E: content_bottom
                    F: footer

        rzcms_blog_post:
            path: 'RzPageBundle:theme\rzcms:blog_post.html.twig'
            name: 'Blog Post'
            containers:
                content_top:
                    name: Content Top
                content:
                    name: Main Content
                content_bottom:
                    name: Content Bottom
                footer:
                    name: footer
                    shared: true
            matrix:
                layout: |
                    AAAAAAAAAAAA
                    CCCCCCCCCCCC
                    CCCCCCCCCCCC
                    CCCCCCCCCCCC
                    EEEEEEEEEEEE
                    FFFFFFFFFFFF
                mapping:
                    A: content_top
                    C: content
                    E: content_bottom
                    F: footer
        rzcms_gallery:
            path: 'RzPageBundle:theme\rzcms:gallery.html.twig'
            name: 'Gallery'
            containers:
                content_top:
                    name: Content Top
                content:
                    name: Main Content
                content_bottom:
                    name: Content Bottom
                footer:
                    name: footer
                    shared: true
            matrix:
                layout: |
                    AAAAAAAAAAAA
                    CCCCCCCCCCCC
                    CCCCCCCCCCCC
                    CCCCCCCCCCCC
                    EEEEEEEEEEEE
                    FFFFFFFFFFFF
                mapping:
                    A: content_top
                    C: content
                    E: content_bottom
                    F: footer
        rzcms_user_profile:
            path: 'RzPageBundle:theme\rzcms:profile.html.twig'
            name: 'User Profile'
            containers:
                content_top:
                    name: Content Top
                content:
                    name: Main Content
                content_bottom:
                    name: Content Bottom
                footer:
                    name: footer
                    shared: true
            matrix:
                layout: |
                    AAAAAAAAAAAA
                    CCCCCCCCCCCC
                    CCCCCCCCCCCC
                    CCCCCCCCCCCC
                    EEEEEEEEEEEE
                    FFFFFFFFFFFF
                mapping:
                    A: content_top
                    C: content
                    E: content_bottom
                    F: footer
        rzcms_full:
            path: 'RzPageBundle:theme\rzcms:full.html.twig'
            name: 'Generic Page'
            containers:
                content_top:
                    name: Content Top
                content:
                    name: Main Content
                content_bottom:
                    name: Content Bottom
                footer:
                    name: footer
                    shared: true
            matrix:
                layout: |
                    AAAAAAAAAAAA
                    CCCCCCCCCCCC
                    CCCCCCCCCCCC
                    CCCCCCCCCCCC
                    EEEEEEEEEEEE
                    FFFFFFFFFFFF
                mapping:
                    A: content_top
                    C: content
                    E: content_bottom
                    F: footer
        rz_user_security:
            path: 'RzUserSecurityBundle:Layout:security.html.twig'
            name: 'Security Template'
            containers:
                content:
                    name: Main Content
                footer:
                    name: footer
                    shared: true
            matrix:
                layout: |
                    CCCCCCCCCCCC
                    CCCCCCCCCCCC
                    CCCCCCCCCCCC
                    FFFFFFFFFFFF
                mapping:
                    C: content
                    F: footer
        rzcms_exception_404:
            path: 'RzPageBundle:theme\rzcms:error404.html.twig'
            name: 'Exception 404'
        rzcms_exception_500:
            path: 'RzPageBundle:theme\rzcms:error500.html.twig'
            name: 'Exception 500'

    page_defaults:
        homepage: {decorate: false, enabled: true}

#    assets:
#        stylesheets:
#            # Defaults:
#            - assetic/sonata_front_css.css
#            - assetic/sonata_front_font_css.css
#            - assetic/sonata_front_edit_css.css
#            - assetic/sonata_front_edit2_css.css
#            - assetic/sonata_front_theme_css.css
#            - assetic/sonata_front_theme2_css.css
#            - assetic/sonata_front_theme_override_css.css
#
#        javascripts:
#            # Defaults:
#            - assetic/sonata_front_js.js
#            - assetic/sonata_front_edit_js.js
#            - assetic/sonata_front_theme_js.js

    caches:
#         esi:
#            token: %sonata_page_cache_esi_token%
#            version: 3
#            servers:
#                # you need to ajust this configuration to match your varnish configuration
#                - %sonata_page.varnish.command%
         ssi:
            token: %sonata_page_cache_ssi_token% #add an unique token here # default is a random value

    catch_exceptions:
        not_found: [404]    # render 404 page with "not_found" key (name generated: _page_internal_error_{key})
        fatal:     [500]    # so you can use the same page for different http errors or specify specific page for each error

    is_inline_edition_on: true

# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataPageBundle: ~
                    SonataPageBundle: ~
