#
# more information can be found here http://sonata-project.org/bundles/admin
#
sonata_admin:
    # default value, change it to sonata.admin.security.handler.acl to use ACL
    security:
        handler: sonata.admin.security.handler.role

    title:      %sonata_admin.title%
    title_logo: %sonata_admin.logo_title%
    options:
        html5_validate: false # does not use html5 validation
        pager_links: 5 # pager max links to display
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default value if done set, actions templates, should extends a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig

    dashboard:
        blocks:
            ######
            # PIWIK BUNDLE
            #####
            #- { position: top, type: rz_piwik.block.piwik_widget, settings: { mode: admin, title: Visits Overtime (Analytics), widgetCode: '<div id="widgetIframe"><iframe width="100%" height="270" src="%rz_pwik_hostname%/index.php?module=Widgetize&action=iframe&columns[]=nb_visits&widget=1&moduleToWidgetize=VisitsSummary&actionToWidgetize=getEvolutionGraph&idSite=1&period=day&date=today&disableLink=1&widget=1" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe></div>' } }
            #- { position: left, type: rz_piwik.block.piwik_widget, settings: { mode: admin, title: Real Time Visitor (Analytics), widgetCode: '<div id="widgetIframe"><iframe width="100%" height="200" src="http://piwik.local/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=Live&actionToWidgetize=getSimpleLastVisitCount&idSite=1&period=day&date=today&disableLink=1&widget=1" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe></div>' } }
            #- { position: left, type: rz_piwik.block.piwik_widget, settings: { mode: admin, title: Visitor Map (Analytics), widgetCode: '<div id="widgetIframe"><iframe width="100%" height="390" src="http://piwik.local/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=UserCountryMap&actionToWidgetize=visitorMap&idSite=1&period=day&date=today&disableLink=1&widget=1" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe></div>' } }
            #- { position: left, type: rz_piwik.block.piwik_widget, settings: { mode: admin, title: Device Type (Analytics), widgetCode: '<div id="widgetIframe"><iframe width="100%" height="480" src="http://piwik.local/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=DevicesDetection&actionToWidgetize=getType&idSite=1&period=day&date=today&disableLink=1&widget=1" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe></div>' } }
            #- { position: left, type: rz_piwik.block.piwik_widget, settings: { mode: admin, title: Browser Engine (Analytics), widgetCode: '<div id="widgetIframe"><iframe width="100%" height="320" src="http://piwik.local/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=DevicesDetection&actionToWidgetize=getBrowserEngines&idSite=1&period=day&date=today&disableLink=1&widget=1" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe></div>' } }
            ######
            # GOOGLE API BUNDLE
            #####
            #- { position: top, type: rz_google_api_client.block.admin_ga_site_traffic, settings: { mode: admin, title: Google Analytics } }
            - { position: top, type: sonata.block.service.text, settings: { content: "<h2>rzproject cms-sandbox</h2> <p>CMS built on top of Synfony2 and SonataBundles.</p>"} }
            - { position: left, type: sonata.admin.block.admin_list }
            - { position: left, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: http://sonata-project.org/blog/archive.rss, mode: admin }}
            - { position: center, type: rz.user.block.profile_gender_graph, settings: { title: Overall User Gender, mode: admin }}
            - { position: center, type: rz.user.block.profile_age_graph, settings: { title: Overall User Age, mode: admin }}
            - { position: center, type: rz.user.block.user_authentication_logs_graph, settings: { title: Recent User Login, mode: admin }}
            - { position: center, type: rz.user.block.user_registration_graph, settings: { title: Registration, mode: admin, fetchCountRecord: 7 }}
            - { position: right, type: rz_news.block.all_time_popular_posts, settings: { title: Trending Posts, number: 5, mode: admin }}
            - { position: right, type: sonata.news.block.recent_posts, settings: { title: Recent Posts, number: 5, mode: admin }}
            - { position: right, type: sonata.news.block.recent_comments, settings: { title: Recent Comments, number: 5, mode: admin }}
#            - { position: center, type: sonata.timeline.block.timeline, settings: { context: SONATA_ADMIN, max_per_page: 10 }}

        groups:
            CMS:
                items:
                   - sonata.page.admin.site
                   - sonata.page.admin.page
                   - sonata.page.admin.shared_block
                   - sonata.media.admin.media
                   - sonata.media.admin.gallery
                   - sonata.news.admin.post
                   - sonata.news.admin.comment
            System:
                items:
                   - sonata.classification.admin.context
                   - sonata.classification.admin.collection
                   - sonata.classification.admin.category
                   - sonata.classification.admin.tag
                   - sonata.notification.admin.message
            User:
                items:
                   - sonata.user.admin.user
                   - sonata.user.admin.group
#    assets:
#        stylesheets:
#            # The sandbox includes default pre-optimized version of some css and js
#            # So you can either use them, and add your custom assets here
#            #   ~ or ~
#            # tweak the assetic.yml and the following lines
#            - assetic/sonata_admin_css.css
#
#        javascripts:
#            - assetic/sonata_admin_js.js